### ISSUE TITLE
Report Documentation

### ISSUE THREAD

**Issue by Aryamant21** [UQdeco3500/TheLastofUs#1]
# **Description**
**Task:** Derive insights from user interviews and complete report

Prepare thorough documentation for the contextual analysis done throughout the research phase of the project. Organizing, condensing, and presenting the results of the contextual enquiry process are the tasks involved in this assignment. Clear explanations of the user behavior, requirements, and pain areas identified through in-depth interviews and observations should be included in the documentation. This involves creating a complete report of o=the progress made.

# **Milestones**
Steps that need to be completed for this task.
- [x] (Sep. 23) - User Interviews and insights
- [x] (Sep. 25) - Scenarios and user persona
- [x] (Sep. 26) - Storyboard
- [x] (Sep. 29) - Change in plans
- [x] ( Oct. 8) - Prototype details
- [x] ( Oct. 10) - Final Submission

**Completion Deadline:** Oct. 10

**Expected Outcome:**
Documentation will be a great resource for the project team, assisting in informed design decisions, feature prioritization, and user-centered development. It will give a full insight of user behaviors, needs, and pain spots, resulting in a better user-friendly product.

# **Members** 
Manvi Narang (ManviNarang01)
Ibnu (ibnumuharam)
