### ISSUE TITLE
Developing Prototypes

### ISSUE THREAD

**Issue by Aryamant21** [UQdeco3500/TheLastofUs#2]
# **Description**
**Task:** Create high fidelity prototype

Create interactive user interface prototypes to illustrate and illustrate the project's design principles. These prototypes will act as a physical illustration of the functionality and user experience, enabling early evaluation, comments, and confirmation of the design intent.

# **Milestones**
Steps that need to be completed for this task.
- [x] (Sep. 23) - Finalizing features for the project
- [x] (Sep. 27) - Low Fidelity prototype
- [x] (Sep. 30) - Change in plans
- [ ] (Oct. 8) - Final High Fidelity Prototype

 
**Completion Deadline:** Oct. 8

**Expected Outcome:**
The user interface prototypes will give a visual and interactive representation of the project's design principles. These prototypes will provide early testing and feedback, allowing the project team to tweak the design and make informed judgements regarding the user experience.

# **Members** 
Rohan (RohanTeo)
Jeff (jefdav10566)
