### ISSUE TITLE
Code Final Project

### ISSUE THREAD

**Issue by Aryamant21** [UQdeco3500/TheLastofUs#3]
# **Description**
**Task:** Implement the decided features 

Code the decided features according to the project's requirements. This role entails developing and implementing the user interface, coding features, and providing an environment that allows for coding in a variety of computer languages. The objective is to provide a coding platform that is both user-friendly and efficient.

# **Milestones**
Steps that need to be completed for this task.
- [x] (Sep. 26) - Finalize Database for AI model
- [x] (Sep. 29) - Build Rough Application Based on the low fidelity prototype
- [x] (Oct. 5) - Implement AI for smart mirror
- [x] (Oct. 8) - Implement final application frontend
- [x] (Oct. 10) - Integrate AI and Application
- [x] (Oct. 12) - Final project

 
**Completion Deadline:** Oct. 12

**Expected Outcome:**
The AI Mirror integration will result in a more engaging and personalized user interface, Users will enjoy a more smooth and intelligent mirror experience with enhanced functionality and responsiveness.

# **Members** 
Aryaman (Aryamant21)
